name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # - name: Set up SSH for AUR
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.AUR_KEY }}" > ~/.ssh/aur_rsa
      #     chmod 600 ~/.ssh/aur_rsa
      #     ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
